version: "3"
services:
  fastapi_app:
    container_name: fastapi_app
    image: emrecetinkayadev/fastapi-demo-project:1.0.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://postgres:password123@postgres:5432/fastapi
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
